### Obtención de todos los productos
GET http://localhost:1234/productos/

### Obtención de un producto específico
GET http://localhost:1234/productos/3/

### Agregado de un producto nuevo
POST http://localhost:1234/productos
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME",
    "tipo": "Electrodoméstico de cocina",
    "precio": 150.15
}

### Actualización de un producto
PATCH http://localhost:1234/productos/10
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

### Borrado de un producto
DELETE http://localhost:1234/productos/8


### 1. OBTENCIÓN DE TODOS LOS USUARIOS
GET http://localhost:1234/usuarios/


### 2. OBTENCIÓN DE UN USUARIO EN ESPECÍFICO
GET http://localhost:1234/usuarios/1/


### 3. AGREGAR UN NUEVO USUARIO
POST http://localhost:1234/usuarios
Content-Type: application/json

{
    "nombre": "Jimena Hernández",
    "edad": 38,
    "email": "jimenitahot@gmail.com",
    "telefono": "+54 92395-243578"
}

### 4. MODIFICAR UN DATO DE UN USUARIO
PATCH http://localhost:1234/usuarios/4
Content-Type: application/json

{
    "telefono": "+1 118-415-8972"
}

### 5. BORRAR UN USUARIO
DELETE http://localhost:1234/usuarios/5

### 6. OBTENCIÓN DEL PRECIO DE UN PRODUCTO
GET http://localhost:1234/productos/precio/3

### 7. OBTENCIÓN DLE NOMBRE DE UN PRODUCTO

GET http://localhost:1234/productos/nombre/2

### 8. OBTENCIÓN DEL TELÉFONO DE UN USUARIO

GET http://localhost:1234/usuarios/telefono/7

### 9. ONTENCIÓN DLE NOMBRE DE UN USUARIO

GET http://localhost:1234/usuarios/nombre/9

### 10. CANTIDAD TOTAL DE PRODUCTOS Y SUMATORIA DE SUS PRECIOS

GET http://localhost:1234/productos/estadistica

###Reemplazar un usuario
PUT http://localhost:1234/usuarios/2
Content-Type: application/json

{
    "nombre": "Pamela López",
    "edad": 22,
    "email": "pampam@gmail.com",
    "telefono": "+1 427-345-3578"
}

###Reemplazar un producto
PUT http://localhost:1234/productos/1
Content-Type: application/json

{
    "nombre": "Balanza electrónica",
    "tipo": "Electrodoméstico de cocina",
    "precio": 120.50
}

###Agrego otro usuario
POST http://localhost:1234/usuarios
Content-Type: application/json

{
    "nombre": "Noelia Albarracín",
    "edad": 35,
    "email": "noelamojigata@gmail.com",
    "telefono": "+1 923-756-3578"
}


