### Obtencion de todos los productos
GET http://localhost:1234/productos/

### Obtención de un producto específico

GET http://localhost:1234/productos/3/

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:1234/productos
Content-Type: application/json

{
    "id": 11,
    "nombre": "Mixer multiuso ACME",
    "tipo": "Electrodoméstico de cocina",
    "precio": 150.15
}

### Actualización de un producto

PATCH http://localhost:1234/productos/10
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

### Borrado de un producto
DELETE http://localhost:1234/productos/8


### 1. Obtención de todos los usuarios
GET http://localhost:1234/usuarios/

### Obtención de los datos de un usuario específico

GET http://localhost:1234/usuarios/1/

### 3. Agregar un usuario nuevo
POST http://localhost:1234/usuarios
Content-Type: application/json

{
    "id": 11,
    "nombre": "Jimena Hernández",
    "edad": 38,
    "email": "jimenitahot@gmail.com",
    "telefono": "+54 92395-243578"
}

### 4. Modificar un dato de un usaurio

PATCH http://localhost:1234/usuarios/11
Content-Type: application/json

{
    "telefono": "+1 118-415-8972"
}


### 5. Borrar un usuario
DELETE http://localhost:1234/usuarios/5

### 6. Obtención del precio de un producto específico

GET http://localhost:1234/productos/precio/3

### 7. Obtención del nombre de un producto específico

GET http://localhost:1234/productos/nombre/2

### 8. Obtención del teléfono de un usuario específico

GET http://localhost:1234/usuarios/telefono/7

### 9. Obtención del nombre de un usuario específico

GET http://localhost:1234/usuarios/nombre/9

### 10. cantidad total de productos y sumatoria de sus precios (no anda)

GET http://localhost:1234/productos/estadistica






